name: matrix
version: 0.0.0
homepage: https://github.com/morloc-lib/matrix
synopsis: 2D matrix datatypes and operations
description: 2D matrix datatypes and operations
category: math
license: MIT
author: "Zebulun Arendsee"
maintainer: "zbwrnz@gmail.com"
github: https://github.com/morloc-lib/matrix
bug-reports: https://github.com/morloc-lib/matrix
